#!/usr/bin/env php
<?php

if(isset($argv[1])){
    if($argv[1] == 'make:section'){
		if ( !empty( $argv[2] ) ) {
			recurse_copy_template(__DIR__ . '/lib/cli/section', __DIR__ . '/blocks/sections/' . $argv[2], $argv[2]);
		}else{
			echo 'Error';
		}
    }
}

function recurse_copy_template($src, $dst, $templateName) {
	$dir = opendir($src);
	@mkdir($dst);
	while(false !== ( $file = readdir($dir)) ) {
		if (( $file != '.' ) && ( $file != '..' )) {
			$new_file_name = str_replace('{{name}}', $templateName, $file);

			if ( is_dir($src . '/' . $file) ) {
				recurse_copy_template($src . '/' . $file,$dst . '/' . $new_file_name, $templateName);
			}
			else {
				copy($src . '/' . $file,$dst . '/' . $new_file_name);
			}
		}
	}
	closedir($dir);
}

